# Generated by Django 4.2.20 on 2025-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("name", models.CharField(max_length=30)),
                ("assignedtp", models.CharField(max_length=30)),
                ("priority", models.IntegerField()),
            ],
        ),
    ]
